'use server';

/**
 * @fileOverview This file defines a Genkit flow for generating product descriptions based on images and basic product information.
 *
 * It exports:
 * - `generateProductDescription`: An async function that takes `GenerateProductDescriptionInput` and returns a `Promise` of `GenerateProductDescriptionOutput`.
 * - `GenerateProductDescriptionInput`: The input type for the generateProductDescription function.
 * - `GenerateProductDescriptionOutput`: The return type for the generateProductDescription function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateProductDescriptionInputSchema = z.object({
  productName: z.string().describe('The name of the product.'),
  productCategory: z.string().describe('The category of the product.'),
  productImage: z
    .string()
    .describe(
      "A photo of the product, as a data URI that must include a MIME type and use Base64 encoding. Expected format: 'data:<mimetype>;base64,<encoded_data>'."
    ),
  productDetails: z.string().describe('Additional details about the product.'),
});

export type GenerateProductDescriptionInput = z.infer<
  typeof GenerateProductDescriptionInputSchema
>;

const GenerateProductDescriptionOutputSchema = z.object({
  productDescription: z
    .string()
    .describe('A compelling product description generated by AI.'),
});

export type GenerateProductDescriptionOutput = z.infer<
  typeof GenerateProductDescriptionOutputSchema
>;

export async function generateProductDescription(
  input: GenerateProductDescriptionInput
): Promise<GenerateProductDescriptionOutput> {
  return generateProductDescriptionFlow(input);
}

const generateProductDescriptionPrompt = ai.definePrompt({
  name: 'generateProductDescriptionPrompt',
  input: {schema: GenerateProductDescriptionInputSchema},
  output: {schema: GenerateProductDescriptionOutputSchema},
  prompt: `You are an expert in writing compelling product descriptions for an online marketplace.

  Based on the following information, generate a product description that will attract potential buyers:

  Product Name: {{{productName}}}
  Category: {{{productCategory}}}
  Image: {{media url=productImage}}
  Details: {{{productDetails}}}

  Write a description that is engaging, informative, and highlights the key features and benefits of the product.
`,
});

const generateProductDescriptionFlow = ai.defineFlow(
  {
    name: 'generateProductDescriptionFlow',
    inputSchema: GenerateProductDescriptionInputSchema,
    outputSchema: GenerateProductDescriptionOutputSchema,
  },
  async input => {
    const {output} = await generateProductDescriptionPrompt(input);
    return output!;
  }
);
